// Generated by CoffeeScript 1.7.1
var data, progeny;

data = '@import "no-dep"\n\nhtml\n  background-color black';

progeny = require('./index')({
  shallow: true
});

progeny(data, 'dependencies/one-dep.styl', function(err, dependencies) {
  return console.log(dependencies);
});
